name: dnd
version: 0.1.0
author: Marco Jakob <majakob@gmx.ch>
description: Drag and Drop for Dart Web Apps with Mouse and Touch Support.
homepage: https://github.com/marcojakob/dart-dnd
dependencies:
  browser: any
  logging: any
