name: dnd
version: 0.1.0
author: Marco Jakob <majakob@gmx.ch>
description: Drag and Drop for Dart web apps with mouse and touch support.
homepage: http://code.makery.ch/library/dart-drag-and-drop/
documentation: http://www.dartdocs.org/documentation/dnd/0.1.0/
dependencies:
  browser: any
  logging: any
