name: dnd
version: 0.0.1
author: Marco Jakob <majakob@gmx.ch>
description: Tracks mouse and touch dragging and dropping.
homepage: https://github.com/marcojakob/dart-dnd
dependencies:
  browser: any
  logging: any
dev_dependencies:
  intl: any
  bootstrap_for_pub: any
