name: dnd_example_shadow_dom
version: 0.0.0
author: Marco Jakob <majakob@gmx.ch>
description: 'Dart Drag and Drop Example'
homepage: http://code.makery.ch/library/dart-drag-and-drop/
dependencies:
  browser: any
  polymer: any
  dnd:
    path: ../../
transformers:
- polymer:
    entry_points: web/index.html
